[package]
name              = "gaze-bench"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
gaze-core   = { workspace = true }
gaze-snap   = { workspace = true }
gaze-detect = { workspace = true }
anyhow      = { workspace = true }
clap        = { workspace = true }
image       = { workspace = true }
rand        = { workspace = true }
rand_distr  = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
rayon       = "1"

[[bin]]
name = "gaze-bench"
path = "src/bin/gaze-bench.rs"
