[package]
name    = "gaze-provider-synthetic"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
gaze-core          = { workspace = true }
anyhow             = { workspace = true }
thiserror          = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
clap               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
rand               = { workspace = true }
rand_distr         = { workspace = true }
crossbeam-channel  = { workspace = true }
glam               = { workspace = true }
evdev              = "0.13"

[dev-dependencies]
tempfile           = "3"

[[bin]]
name = "gaze-provider-cli"
path = "src/bin/gaze-provider-cli.rs"

[lints.clippy]
# The workspace style mandates explicit `Foo { x: x }` field syntax everywhere.
redundant_field_names = "allow"
